# Generated by Django 4.0.4 on 2022-05-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliapp', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
