# Generated by Django 4.0.4 on 2022-05-05 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_date_alter_blog_description_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 5, 13, 6, 18, 677197, tzinfo=utc)),
        ),
    ]
